Update learn-github-actions.yml

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -12,8 +12,8 @@ jobs:
         run: |
           # Change "cheese" to the word you want to catch
           if git grep -q "cheese" ; then
-            echo "::error::cheese word found! The build failed."
-            exit 1
+            echo "::error::cheese word found! The is good."
           else
-            echo "cheese word not found. Proceeding..."
+            echo "cheese word not found. failing..."
+            exit 1
           fi
